=== dukevin/sandwich/customize/resource/automatic/Wik/sty.dtd
<!ELEMENT Resource (Map)>
<!ATTLIST Resource	type (aamap) "aamap"
			name CDATA #REQUIRED
			version CDATA #REQUIRED
			author CDATA "Anonymous"
			category CDATA "unsorted"
			comissioner CDATA #IMPLIED
			>
<!ELEMENT Map (Settings?,World)>
<!ATTLIST Map		version CDATA #REQUIRED>
<!ELEMENT Settings (Setting*)>
<!ELEMENT Setting EMPTY>
<!ATTLIST Setting	name CDATA #REQUIRED
			value CDATA #REQUIRED
			>
<!ELEMENT World (Field)>
<!ELEMENT Field (Axes?,(Spawn|Wall|Zone)*)>
<!ATTLIST Field		logicalBox (true|false) "true"
			>
<!ELEMENT Axes (Axis*)>
<!ATTLIST Axes		number CDATA "4"
			normalize (true|false) "true"
			>
<!ELEMENT Axis EMPTY>
<!ATTLIST Axis		xdir CDATA #IMPLIED
			ydir CDATA #IMPLIED
			angle CDATA #IMPLIED
			length CDATA "1.0"
			>
<!ELEMENT Spawn EMPTY>
<!ATTLIST Spawn		x CDATA #REQUIRED
			y CDATA #REQUIRED
			xdir CDATA #IMPLIED
			ydir CDATA #IMPLIED
			angle CDATA #IMPLIED
			length CDATA "1.0"
			>
<!ELEMENT Wall (Point+)>
<!ATTLIST Wall		height CDATA #IMPLIED
			>
<!ELEMENT Zone (ShapeCircle)>
<!ATTLIST Zone		effect (win|death|fortress|ball|flag|target|rubber|sumo) "death"
			rubberVal CDATA "0.0"
			>
<!ELEMENT ShapeCircle (Point)>
<!ATTLIST ShapeCircle	radius CDATA #REQUIRED
			growth CDATA "0.0"
			>
<!ELEMENT Point EMPTY>
<!ATTLIST Point		x CDATA #REQUIRED
			y CDATA #REQUIRED
			>

=== dukevin/sandwich/customize/resource/automatic/Wik/dogfight/silo-110714.aamap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Resource SYSTEM "Wik/sty.dtd"> 
<Resource type="aamap" author="Wik" category="dogfight" name="silo" version="110714">
<Map version="2">
<World>
<Field>
<Spawn x="30" y="81.5" angle="0"/>
<Spawn x="243.2" y="30" angle="90"/>
<Spawn x="213.8" y="221.5" angle="180"/>
<Spawn x="81.5" y="132.9" angle="270"/>
<Spawn x="192.3" y="81.5" angle="0"/>
<Spawn x="162.3" y="170.1" angle="90"/>
<Spawn x="132.3" y="81.5" angle="180"/>
<Spawn x="243.2" y="132.9" angle="270"/>
<Spawn x="110.9" y="221.5" angle="0"/>
<Spawn x="81.5" y="30" angle="90"/>
<Spawn x="294.6" y="81.5" angle="180"/>
<Spawn x="162.3" y="273" angle="270"/>
<Wall>
<Point x="210.9" y="156.3"/>
<Point x="211.1" y="156.3"/>
<Point x="211.3" y="156.4"/>
<Point x="211.4" y="156.5"/>
<Point x="218.9" y="159.2"/>
<Point x="226.7" y="161.2"/>
<Point x="234.8" y="162.5"/>
<Point x="243.2" y="162.9"/>
<Point x="251.5" y="162.5"/>
<Point x="259.6" y="161.2"/>
<Point x="267.4" y="159.2"/>
<Point x="274.9" y="156.5"/>
<Point x="282" y="153.1"/>
<Point x="288.7" y="149"/>
<Point x="295" y="144.3"/>
<Point x="300.7" y="139"/>
<Point x="306" y="133.3"/>
<Point x="310.7" y="127"/>
<Point x="314.8" y="120.3"/>
<Point x="318.2" y="113.2"/>
<Point x="320.9" y="105.7"/>
<Point x="322.9" y="97.9"/>
<Point x="324.2" y="89.8"/>
<Point x="324.6" y="81.5"/>
<Point x="324.2" y="73.1"/>
<Point x="322.9" y="65"/>
<Point x="320.9" y="57.2"/>
<Point x="318.2" y="49.7"/>
<Point x="314.8" y="42.6"/>
<Point x="310.7" y="35.9"/>
<Point x="306" y="29.6"/>
<Point x="300.7" y="23.9"/>
<Point x="295" y="18.6"/>
<Point x="288.7" y="13.9"/>
<Point x="282" y="9.8"/>
<Point x="274.9" y="6.4"/>
<Point x="267.4" y="3.7"/>
<Point x="259.6" y="1.7"/>
<Point x="251.5" y="0.4"/>
<Point x="243.2" y="0"/>
<Point x="234.8" y="0.4"/>
<Point x="226.7" y="1.7"/>
<Point x="218.9" y="3.7"/>
<Point x="211.4" y="6.4"/>
<Point x="204.3" y="9.8"/>
<Point x="197.6" y="13.9"/>
<Point x="191.3" y="18.6"/>
<Point x="185.6" y="23.9"/>
<Point x="180.3" y="29.6"/>
<Point x="175.6" y="35.9"/>
<Point x="171.5" y="42.6"/>
<Point x="168.1" y="49.7"/>
<Point x="165.4" y="57.2"/>
<Point x="163.4" y="65"/>
<Point x="162.3" y="72"/>
<Point x="161.2" y="65"/>
<Point x="159.2" y="57.2"/>
<Point x="156.5" y="49.7"/>
<Point x="153.1" y="42.6"/>
<Point x="149" y="35.9"/>
<Point x="144.3" y="29.6"/>
<Point x="139" y="23.9"/>
<Point x="133.3" y="18.6"/>
<Point x="127" y="13.9"/>
<Point x="120.3" y="9.8"/>
<Point x="113.2" y="6.4"/>
<Point x="105.7" y="3.7"/>
<Point x="97.9" y="1.7"/>
<Point x="89.8" y="0.4"/>
<Point x="81.5" y="0"/>
<Point x="73.1" y="0.4"/>
<Point x="65" y="1.7"/>
<Point x="57.2" y="3.7"/>
<Point x="49.7" y="6.4"/>
<Point x="42.6" y="9.8"/>
<Point x="35.9" y="13.9"/>
<Point x="29.6" y="18.6"/>
<Point x="23.9" y="23.9"/>
<Point x="18.6" y="29.6"/>
<Point x="13.9" y="35.9"/>
<Point x="9.8" y="42.6"/>
<Point x="6.4" y="49.7"/>
<Point x="3.7" y="57.2"/>
<Point x="1.7" y="65"/>
<Point x="0.4" y="73.1"/>
<Point x="0" y="81.5"/>
<Point x="0.4" y="89.8"/>
<Point x="1.7" y="97.9"/>
<Point x="3.7" y="105.7"/>
<Point x="6.4" y="113.2"/>
<Point x="9.8" y="120.3"/>
<Point x="13.9" y="127"/>
<Point x="18.6" y="133.3"/>
<Point x="23.9" y="139"/>
<Point x="29.6" y="144.3"/>
<Point x="35.9" y="149"/>
<Point x="42.6" y="153.1"/>
<Point x="49.7" y="156.5"/>
<Point x="57.2" y="159.2"/>
<Point x="65" y="161.2"/>
<Point x="73.1" y="162.5"/>
<Point x="81.5" y="162.9"/>
<Point x="89.8" y="162.5"/>
<Point x="97.9" y="161.2"/>
<Point x="105.7" y="159.2"/>
<Point x="113.2" y="156.5"/>
<Point x="113.7" y="156.3"/>
<Point x="110.5" y="158.6"/>
<Point x="104.7" y="163.9"/>
<Point x="99.4" y="169.7"/>
<Point x="94.8" y="176"/>
<Point x="90.7" y="182.7"/>
<Point x="87.3" y="189.8"/>
<Point x="84.5" y="197.3"/>
<Point x="82.5" y="205.1"/>
<Point x="81.3" y="213.2"/>
<Point x="80.9" y="221.5"/>
<Point x="81.3" y="229.8"/>
<Point x="82.5" y="237.9"/>
<Point x="84.5" y="245.7"/>
<Point x="87.3" y="253.2"/>
<Point x="90.7" y="260.3"/>
<Point x="94.8" y="267"/>
<Point x="99.4" y="273.3"/>
<Point x="104.7" y="279.1"/>
<Point x="110.5" y="284.4"/>
<Point x="116.8" y="289"/>
<Point x="123.5" y="293.1"/>
<Point x="130.6" y="296.5"/>
<Point x="138.1" y="299.3"/>
<Point x="145.9" y="301.3"/>
<Point x="154" y="302.5"/>
<Point x="162.3" y="303"/>
<Point x="170.6" y="302.5"/>
<Point x="178.7" y="301.3"/>
<Point x="186.5" y="299.3"/>
<Point x="194" y="296.5"/>
<Point x="201.1" y="293.1"/>
<Point x="207.8" y="289"/>
<Point x="214.1" y="284.4"/>
<Point x="219.9" y="279.1"/>
<Point x="225.2" y="273.3"/>
<Point x="229.8" y="267"/>
<Point x="233.9" y="260.3"/>
<Point x="237.3" y="253.2"/>
<Point x="240.1" y="245.7"/>
<Point x="242.1" y="237.9"/>
<Point x="243.3" y="229.8"/>
<Point x="243.8" y="221.5"/>
<Point x="243.3" y="213.2"/>
<Point x="242.1" y="205.1"/>
<Point x="240.1" y="197.3"/>
<Point x="237.3" y="189.8"/>
<Point x="233.9" y="182.7"/>
<Point x="229.8" y="176"/>
<Point x="225.2" y="169.7"/>
<Point x="219.9" y="163.9"/>
<Point x="214.1" y="158.6"/>
<Point x="210.9" y="156.3"/>
</Wall>
<Wall>
<Point x="194" y="146.5"/>
<Point x="186.5" y="143.7"/>
<Point x="178.7" y="141.7"/>
<Point x="170.6" y="140.5"/>
<Point x="162.3" y="140.1"/>
<Point x="154" y="140.5"/>
<Point x="145.9" y="141.7"/>
<Point x="138.1" y="143.7"/>
<Point x="130.6" y="146.5"/>
<Point x="130" y="146.8"/>
<Point x="133.3" y="144.3"/>
<Point x="139" y="139"/>
<Point x="144.3" y="133.3"/>
<Point x="149" y="127"/>
<Point x="153.1" y="120.3"/>
<Point x="156.5" y="113.2"/>
<Point x="159.2" y="105.7"/>
<Point x="161.2" y="97.9"/>
<Point x="162.3" y="91"/>
<Point x="163.4" y="97.9"/>
<Point x="165.4" y="105.7"/>
<Point x="168.1" y="113.2"/>
<Point x="171.5" y="120.3"/>
<Point x="175.6" y="127"/>
<Point x="180.3" y="133.3"/>
<Point x="185.6" y="139"/>
<Point x="191.3" y="144.3"/>
<Point x="194.6" y="146.8"/>
<Point x="194" y="146.5"/>
</Wall>
</Field>
</World>
</Map>
</Resource>

=== dukevin/sandwich/customize/resource/automatic/rxfreaks/hft/compass-4.aamap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Resource SYSTEM "sty.dtd"> 
<Resource type="aamap" name="compass" version="4" author="rxfreaks" category="hft">
<Map version="0.2.8">
 <Settings>
	<Setting name="delay_command" value="r0 100 spawn_zone teleport 128 240 .5 0 0 0 240 240 abs 1 1 1 false 0 .1 0" />
	<Setting name="delay_command" value="r0 100 spawn_zone teleport 240 128 .5 0 0 0 240 240 abs 1 1 1 false 0 .1 0" />
	<Setting name="delay_command" value="r0 100 spawn_zone teleport 240 352 .5 0 0 0 240 240 abs 1 1 1 false 0 .1 0" />
	<Setting name="delay_command" value="r0 100 spawn_zone teleport 352 240 .5 0 0 0 240 240 abs 1 1 1 false 0 .1 0" />
	<!-- SPAWN_ZONE teleport <x> <y> <size> <growth> <dirx> <diry> <xdest> <ydest> <rel|abs|cycle> <xdirdest> <ydirdest> <relocation_factor><interactive> <r> <g> <b> <target_size> -->
 </Settings>
  <World>
   <Field>
   <Axes number="4"/>

   <Spawn x="464" y="32" xdir="0" ydir="1"/>
   <Spawn x="304" y="32" xdir="0" ydir="1"/>
   <Spawn x="176" y="32" xdir="0" ydir="1"/>
   <Spawn x="32" y="32" xdir="0" ydir="1"/>
   <Spawn x="32" y="480" xdir="0" ydir="-1"/>
   <Spawn x="176" y="480" xdir="0" ydir="-1"/>
   <Spawn x="304" y="480" xdir="0" ydir="-1"/>
   <Spawn x="464" y="480" xdir="0" ydir="-1"/>

   <Wall height="50">
    <Point x="0" y="0"/>
    <Point x="0" y="500"/>
    <Point x="500" y="500"/>
    <Point x="500" y="0"/>
    <Point x="0" y="0"/>
   </Wall>
   <Wall height="5">
    <Point x="208" y="304"/>
    <Point x="240" y="336"/>
    <Point x="272" y="304"/>
    <Point x="240" y="464"/>
    <Point x="208" y="304"/>
   </Wall>
   <Wall height="5">
    <Point x="208" y="176"/>
    <Point x="240" y="144"/>
    <Point x="272" y="176"/>
    <Point x="240" y="32"/>
    <Point x="208" y="176"/>
   </Wall>
   <Wall height="5">
    <Point x="304" y="272"/>
    <Point x="336" y="240"/>
    <Point x="304" y="208"/>
    <Point x="464" y="240"/>
    <Point x="304" y="272"/>
   </Wall>
   <Wall height="5">
    <Point x="176" y="272"/>
    <Point x="144" y="240"/>
    <Point x="176" y="208"/>
    <Point x="32" y="240"/>
    <Point x="176" y="272"/>
   </Wall>

   </Field>
  </World>
 </Map>
</Resource>

=== dukevin/sandwich/customize/resource/automatic/Wik/dogfight/tiles-270612.aamap.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Resource SYSTEM "Wik/sty.dtd">
<Resource type="aamap" author="Wik" category="dogfight" name="tiles" version="270612">
<Map version="2">
<World>
<Field>
<Spawn x="273" y="187" angle="180"/>
<Spawn x="20" y="302" angle="0"/>
<Spawn x="20" y="72" angle="0"/>
<Spawn x="169" y="187" angle="0"/>
<Spawn x="124" y="302" angle="180"/>
<Spawn x="124" y="72" angle="180"/>
<Spawn x="221" y="239" angle="270"/>
<Spawn x="72" y="354" angle="270"/>
<Spawn x="72" y="20" angle="90"/>
<Spawn x="221" y="135" angle="90"/>
<Spawn x="72" y="250" angle="90"/>
<Spawn x="72" y="124" angle="270"/>
<Wall>
<Point x="0" y="0"/>
<Point x="144" y="0"/>
<Point x="144" y="115"/>
<Point x="293" y="115"/>
<Point x="293" y="259"/>
<Point x="144" y="259"/>
<Point x="144" y="374"/>
<Point x="0" y="374"/>
<Point x="0" y="230"/>
<Point x="149" y="230"/>
<Point x="149" y="144"/>
<Point x="0" y="144"/>
<Point x="0" y="0"/>
</Wall>
</Field>
</World>
</Map>
</Resource>

=== dukevin/sandwich/customize/resource/automatic/rxfreaks/hft/hexagon-1.aamap.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Resource SYSTEM "sty.dtd"> 
<Resource type="aamap" name="hexagon" version="1" author="rxfreaks" category="hft">
<Map version="0.2.8">
  <World>
   <Field>
   <Axes number="6"/>

   <Spawn x="255" y="50" xdir="0" ydir="1"/>
   <Spawn x="245" y="450" xdir="0" ydir="-1"/>
   <Spawn x="50" y="245" xdir="1" ydir="0"/>
   <Spawn x="450" y="255" xdir="-1" ydir="0"/>
   <Spawn x="305" y="100" xdir="0" ydir="1"/>
   <Spawn x="195" y="400" xdir="0" ydir="-1"/>
   <Spawn x="100" y="195" xdir="1" ydir="0"/>
   <Spawn x="400" y="305" xdir="-1" ydir="0"/>
   <Spawn x="205" y="100" xdir="0" ydir="1"/>
   <Spawn x="295" y="400" xdir="0" ydir="-1"/>
   <Spawn x="100" y="295" xdir="1" ydir="0"/>
   <Spawn x="400" y="205" xdir="-1" ydir="0"/>

   <Wall>
    <Point x="-16" y="240"/>
    <Point x="112" y="496"/>
    <Point x="368" y="496"/>
    <Point x="512" y="256"/>
    <Point x="368" y="16"/>
    <Point x="112" y="16"/>
    <Point x="-16" y="240"/>
   </Wall>

   </Field>
  </World>
 </Map>
</Resource>

=== dukevin/sandwich/customize/resource/automatic/Wik/dogfight/triangle-120714.aamap.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Resource SYSTEM "Wik/sty.dtd"> 
<Resource type="aamap" author="Wik" category="dogfight" name="triangle" version="120714">
<Map version="2">
<World>
<Field>
<Spawn x="186.9" y="171.9" angle="270"/>
<Spawn x="236.9" y="251.9" angle="90"/>
<Spawn x="171.9" y="236.9" angle="180"/>
<Spawn x="251.9" y="186.9" angle="0"/>
<Spawn x="211.9" y="161.9" angle="270"/>
<Spawn x="211.9" y="261.9" angle="90"/>
<Spawn x="161.9" y="211.9" angle="180"/>
<Spawn x="261.9" y="211.9" angle="0"/>
<Spawn x="236.9" y="151.9" angle="270"/>
<Spawn x="186.9" y="271.9" angle="90"/>
<Spawn x="151.9" y="186.9" angle="180"/>
<Spawn x="271.9" y="236.9" angle="0"/>
<Wall>
<Point x="0" y="268.6"/>
<Point x="268.6" y="0"/>
<Point x="367" y="367"/>
<Point x="0" y="268.6"/>
</Wall>
</Field>
</World>
</Map>
</Resource>

=== dukevin/sandwich/customize/resource/automatic/Wik/fortress/Halftime-140813.aamap.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Resource SYSTEM "Wik/sty.dtd">
<Resource type="aamap" name="Halftime" version="140813" author="Wik" category="fortress">
<Map version="2">
<World>
<Field>
<Spawn x="125" y="30" angle="90"/>
<Spawn x="125" y="220" angle="270"/>
<Wall>
<Point x="10" y="240"/>
<Point x="10" y="245"/>
<Point x="15" y="245"/>
<Point x="15" y="250"/>
<Point x="235" y="250"/>
<Point x="235" y="245"/>
<Point x="240" y="245"/>
<Point x="240" y="240"/>
<Point x="245" y="240"/>
<Point x="245" y="235"/>
<Point x="250" y="235"/>
<Point x="250" y="15"/>
<Point x="245" y="15"/>
<Point x="245" y="10"/>
<Point x="240" y="10"/>
<Point x="240" y="5"/>
<Point x="235" y="5"/>
<Point x="235" y="0"/>
<Point x="15" y="0"/>
<Point x="15" y="5"/>
<Point x="10" y="5"/>
<Point x="10" y="10"/>
<Point x="5" y="10"/>
<Point x="5" y="15"/>
<Point x="0" y="15"/>
<Point x="0" y="235"/>
<Point x="5" y="235"/>
<Point x="5" y="240"/>
<Point x="10" y="240"/>
</Wall>
<Wall height="0.01">
<Point x="244" y="9"/>
<Point x="244" y="5"/>
<Point x="245" y="6"/>
<Point x="246" y="5"/>
<Point x="246" y="9"/>
</Wall>
<Wall height="0.01">
<Point x="247" y="9"/>
<Point x="247" y="5"/>
</Wall>
<Wall height="0.01">
<Point x="248" y="9"/>
<Point x="248" y="5"/>
</Wall>
<Wall height="0.01">
<Point x="250" y="9"/>
<Point x="248" y="7"/>
<Point x="250" y="5"/>
</Wall>
<Wall height="0.01">
<Point x="241" y="3"/>
<Point x="242" y="4"/>
<Point x="243" y="3"/>
<Point x="243" y="2"/>
<Point x="241" y="0"/>
<Point x="243" y="0"/>
</Wall>
<Wall height="0.01">
<Point x="244" y="3"/>
<Point x="245" y="4"/>
<Point x="246" y="3"/>
<Point x="246" y="1"/>
<Point x="245" y="0"/>
<Point x="244" y="1"/>
<Point x="244" y="3"/>
</Wall>
<Wall height="0.01">
<Point x="247" y="4"/>
<Point x="247" y="0"/>
</Wall>
<Wall height="0.01">
<Point x="248" y="3"/>
<Point x="249" y="4"/>
<Point x="250" y="3"/>
<Point x="249" y="2"/>
<Point x="250" y="1"/>
<Point x="249" y="0"/>
<Point x="248" y="1"/>
</Wall>
<Zone effect="fortress"><ShapeCircle radius="20"><Point x="125" y="30"/></ShapeCircle></Zone>
<Zone effect="fortress"><ShapeCircle radius="20"><Point x="125" y="220"/></ShapeCircle></Zone>
</Field>
</World>
</Map>
</Resource>
